export const requests = [
  {method: 'loginDashboard', loading: true, success: true, failure: true},
  {method: 'logoutDashboard', loading: true, success: true, failure: true},
  {method: 'addOperator', loading: true, success: true, failure: true},
  {method: 'editOperator', loading: true, success: true, failure: true},
  {method: 'transferOperatorTickets', loading: true, success: true, failure: true},
  {method: 'getOperators', loading: true, success: false, failure: true},
  {method: 'addFAQCategory', loading: true, success: true, failure: true},
  {method: 'editFAQCategory', loading: true, success: true, failure: true},
  {method: 'getFAQCategories', loading: true, success: false, failure: true},
  {method: 'removeFAQCategory', loading: true, success: true, failure: true},
  {method: 'addFAQ', loading: true, success: true, failure: true},
  {method: 'editFAQ', loading: true, success: true, failure: true},
  {method: 'getFAQs', loading: true, success: false, failure: true},
  {method: 'removeFAQ', loading: true, success: true, failure: true},
  {method: 'getTickets', loading: true, success: false, failure: true},
  {method: 'answerTicket', loading: true, success: true, failure: true},
  {method: 'closeTicket', loading: true, success: true, failure: true},
  {method: 'getBugs', loading: true, success: false, failure: true},
  {method: 'closeBug', loading: true, success: true, failure: true},
  {method: 'getTicketConversations', loading: true, success: false, failure: true},
  {method: 'addDefaultAnswer', loading: true, success: true, failure: true},
  {method: 'editDefaultAnswer', loading: true, success: true, failure: true},
  {method: 'RemoveDefaultAnswer', loading: true, success: true, failure: true},
  {method: 'getDefaultAnswers', loading: true, success: false, failure: true}
];
